# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DLC Generator Documentation
email: testing@evergreeninnovations.co
description: >- # this means to ignore newlines until "baseurl:"
  Public Documentation for the DLC Generator tool.
url: "https://evergreen-innovations.github.io/dlc-documentation" # the base hostname & protocol for your site, e.g. http://example.com
breadcrumbs: true
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# theme: minima
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "default" , "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
- jekyll-feed
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache

head_scripts:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: true

# search: true
logo: "/assets/images/dlc-logo.png"

# doc name
doc-name: IEC TS 62600-2
doc-link: https://webstore.iec.ch/publication/62399

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  theory:
    output: true
    permalink: /:collection/:path/:title
  documentation:
    output: true
    permalink: /:collection/:path/:title

atom_feed:
  hide: true

# Defaults
defaults:
  # _theory
  - scope:
      path: ""
      type: theory
    values:
      layout: single
      # classes: wide
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "theory"
  # _usecases
  - scope:
      path: ""
      type: documentation
    values:
      layout: single
      # classes: wide
      author_profile: true
      share: false
      comments: false
      sidebar:
        nav: "documentation"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
